repos:
-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: pipenv run make do_tests
        language: python
        pass_filenames: false
    -   id: styletest
        name: style test
        entry: flake8
        language: python
        pass_filenames: false
    -   id: generate-requirements
        name: generate-requirements
        entry: bash -c 'pipenv requirements >| requirements.txt'
        language: python
        pass_filenames: false
    -   id: generate-dev-requirements
        name: generate-dev-requirements
        entry: bash -c 'pipenv requirements --dev-only >| requirements-dev.txt'
        language: system
        pass_filenames: false
