stages:
  preprocess:
    foreach:
      - ${supervisor.tweets}
      - ${alberta.raw}
      - ${queensland.raw}
      - ${crisis.raw}
    do:
      deps:
        - ${item}
        - src/data/preprocess.py
      cmd: src/data/preprocess.py ${item}
  train:
    deps: 
    # NOTE: Can't include datasets in dependencies, since they are in the form
    # of datasets: <dataset1> <dataset2> instead of a list. Check config.yaml
    # for more info
      - src/train/train.py
    cmd: ./src/train/train.py --env ${env} --model ${model} --label ${label} --download_model -- ${datasets}
    metrics:
      - eval.json
