stages:
  preprocess:
    foreach:
      - ${supervisor.tweets}
      - ${alberta.raw}
      - ${queensland.raw}
    do:
      deps:
        - ${item}
        - src/data/preprocess.py
      cmd: src/data/preprocess.py ${item}
  train:
    deps: 
      - src/train/train.py
    cmd: ./src/train/train.py --env "sagemaker" --model "distilbert-base-uncased" --label "mentions_impact" -- ${supervisor.processed}
