stages:
  preprocess:
    foreach:
      - ${supervisor.tweets}
      - ${alberta.raw}
      - ${queensland.raw}
      - ${crisis.raw}
    do:
      deps:
        - ${item}
        - flood_detection/data/preprocess.py
      cmd: flood_detection/data/preprocess.py ${item}
  train:
    deps:
      # NOTE: Can't include datasets in dependencies, since they are in the form
      # of datasets: <dataset1> <dataset2> instead of a list. Check config.yaml
      # for more info
      - flood_detection/train/train_flood_classifier.py
    cmd: ./flood_detection/train/train_flood_classifier.py --env ${env} --model ${model} --label ${label} --download_model -- ${datasets}
    metrics:
      - eval.json

  geoparser_extract_location:
    deps:
      - ${supervisor.processed}
      - ./flood_detection/predict/extract_location.py
    cmd: ./flood_detection/predict/extract_location.py ${supervisor.processed}
