stages:
  preprocess:
    foreach:
      - ${supervisor.tweets}
      - ${alberta.raw}
      - ${queensland.raw}
    do:
      deps:
        - ${item}
        - ./src/data/preprocess.py
      cmd: ./src/data/preprocess.py ${item}


