env: sagemaker
model: distilbert-base-uncased
label: relevant
datasets: ./data/processed/supervisor_annotated_tweets.csv
models_dir:
  flood_detection: ./models/flood_detection
envs:
  sagemaker: sagemaker
  locally: locally
labels:
  flood_detection: relevant
  mentions_impact: mentions_impact
models:
  distilbert: distilbert-base-uncased
paths:
  tweets: data/tweets
twitter_api:
  tweets: data/tweets/twitter_api
  processed: data/processed/twitter_api
  processed_flood: data/processed_flood/twitter_api
  processed_geo: data/processed_geo/twitter_api
  text_analysis: data/text_analysis/twitter_api
supervisor:
  raw: data/raw/supervisor_annotated_tweets.csv
  tweets: data/tweets/supervisor_annotated_tweets.json
  processed: data/processed/supervisor_annotated_tweets.csv
  processed_flood: data/processed_flood/supervisor_annotated_tweets.csv
  processed_geo: data/processed_geo/supervisor_annotated_tweets.csv
  text_analysis: data/text_analysis/supervisor_annotated_tweets.csv
crisis:
  raw: data/raw/crisis_nlp_task_dmg.tsv
  processed: data/processed/crisis_nlp_task_dmg.csv
alberta:
  raw: data/raw/2013_Alberta_Floods-ontopic_offtopic.csv
  processed: data/processed/2013_Alberta_Floods-ontopic_offtopic.csv
queensland:
  raw: data/raw/2013_Queensland_Floods-ontopic_offtopic.csv
  processed: data/processed/2013_Queensland_Floods-ontopic_offtopic.csv
